### 1 - busca todos os produtos
GET http://localhost:3003/products

### 2 - criar pedido
POST http://localhost:3003/orders/createorder
Content-Type: application/json

{
    "userName": "ILena",
    "deliveryDate": "2022/12/11",
    "products": [
        {
            "name": "BEBIDA ENERGÉTICA VIBE 2L",
            "quantity": 620
        }
    ]
}

### 3 - busca todos os pedidos
GET http://localhost:3003/orders