### 1 - busca todos os produtos
GET http://localhost:3003/products

### 2 - criar pedido
POST http://localhost:3003/orders/createorder
Content-Type: application/json

{
    "userName": "Lua",
    "deliveryDate": "2022/10/10",
    "products": [
        {
            "name": "BEBIDA ENERGÉTICA VIBE 2L",
            "quantity": 5
        }
    ]
}