### 1 - get all products
GET http://localhost:3003/products

### 2 - create order
POST http://localhost:3003/orders/createorder
Content-Type: application/json

{
    "userName": "Nicollas",
    "deliveryDate": "2022/12/11",
    "products": [
        {
            "id": 48,
            "quantity": 900
        }
    ]
}

### 3 - get all orders
GET http://localhost:3003/orders